### ISSUE TITLE
1.2.14: FTBFS "undefined reference to symbol 'pthread_rwlock_destroy@@GLIBC_2.2.5'"

### ISSUE THREAD

**Issue by onlyjob** [oss-tsukuba/gfarm2fs#7]
On Debian _unstable_ 1.2.14 FTBFS as follows:

```
libtool: link: gcc -Wall -g -O2 -ffile-prefix-map=/build/gfarm2fs-1.2.14=. -fstack-protector-strong -Wformat -Werror=format-security -Wl,-z -Wl,relro -Wl,-z -Wl,now -o gfarm2fs_fix_acl gfarm2fs_fix_acl.o acl.o id.o xattr.o gfarm_config.o  -lfuse -lgfarm
/usr/bin/ld: gfarm2fs.o: undefined reference to symbol 'pthread_rwlock_destroy@@GLIBC_2.2.5'
/usr/bin/ld: /lib/x86_64-linux-gnu/libpthread.so.0: error adding symbols: DSO missing from command line
```

1.2.13 builds OK.

**Comment by shuuji3** [comment]
I also encounter a similar error when installing v1.2.14 via spack package using [oss-tsukuba/gfarm-spack](https://github.com/oss-tsukuba/gfarm-spack).

<summary>Error messages:</summary>
<details>
<pre>
$ hostnamectl
   Static hostname: chris61
         Icon name: computer-server
           Chassis: server
        Machine ID: 2021c4d23f764ed2968a3856555d4b5a
           Boot ID: 3c61714ad8734dbf920ddd469b3cb04b
  Operating System: Ubuntu 20.04.1 LTS
            Kernel: Linux 5.4.0-31-generic
      Architecture: x86-64

$ spack install gfarm2fs

(...)

==> Installing gfarm2fs-main-rboxdyz5vhfkby4qa2i63wzv3k3veou4
==> No binary for gfarm2fs-main-rboxdyz5vhfkby4qa2i63wzv3k3veou4 found: installing from source
==> gfarm2fs: Executing phase: 'autoreconf'
==> gfarm2fs: Executing phase: 'configure'
==> gfarm2fs: Executing phase: 'build'
==> Error: ProcessError: Command exited with status 2:
    'make' '-j16'

3 errors found in build log:
     187    mv -f .deps/xattr.Tpo .deps/xattr.Po
     188    /bin/bash ./libtool  --tag=CC   --mode=link /home/shuuji3/src/spack/lib/spack/env/gcc/gcc -Wall -g -O2  -L/home/shuuji3/src/spack/opt/spack/linux-ubuntu20.04-zen/gcc-9.3.0/gfarm-main-ergib3dqflt4lgx6kcgb357phwr6xms5/lib -o gfarm2fs_fix_acl gfarm2fs_fix_acl.o acl.o
             id.o xattr.o gfarm_config.o  -lfuse -lgfarm -lgfarm
     189    libtool: link: /home/shuuji3/src/spack/lib/spack/env/gcc/gcc -Wall -g -O2 -o gfarm2fs_fix_acl gfarm2fs_fix_acl.o acl.o id.o xattr.o gfarm_config.o  -L/home/shuuji3/src/spack/opt/spack/linux-ubuntu20.04-zen/gcc-9.3.0/gfarm-main-ergib3dqflt4lgx6kcgb357phwr6xms5/lib 
            -lfuse -lgfarm
     190    mv -f .deps/gfarm2fs.Tpo .deps/gfarm2fs.Po
     191    /bin/bash ./libtool  --tag=CC   --mode=link /home/shuuji3/src/spack/lib/spack/env/gcc/gcc -Wall -g -O2  -L/home/shuuji3/src/spack/opt/spack/linux-ubuntu20.04-zen/gcc-9.3.0/gfarm-main-ergib3dqflt4lgx6kcgb357phwr6xms5/lib -o gfarm2fs gfarm2fs.o acl.o id.o replicate.
            o open_file.o xattr.o gfarm_config.o  -lfuse -lgfarm -lgfarm
     192    libtool: link: /home/shuuji3/src/spack/lib/spack/env/gcc/gcc -Wall -g -O2 -o gfarm2fs gfarm2fs.o acl.o id.o replicate.o open_file.o xattr.o gfarm_config.o  -L/home/shuuji3/src/spack/opt/spack/linux-ubuntu20.04-zen/gcc-9.3.0/gfarm-main-ergib3dqflt4lgx6kcgb357phwr6x
            ms5/lib -lfuse -lgfarm
  >> 193    /home/linuxbrew/.linuxbrew/bin/ld: gfarm2fs.o: undefined reference to symbol 'pthread_rwlock_destroy@@@@GLIBC_2.2.5'
  >> 194    /home/linuxbrew/.linuxbrew/bin/ld: /lib/x86_64-linux-gnu/libpthread.so.0: error adding symbols: DSO missing from command line
  >> 195    collect2: error: ld returned 1 exit status
     196    make[2]: *** [Makefile:508: gfarm2fs] Error 1
     197    make[2]: Leaving directory '/tmp/shuuji3/spack-stage/spack-stage-gfarm2fs-main-rboxdyz5vhfkby4qa2i63wzv3k3veou4/spack-src'
     198    make[1]: *** [Makefile:644: all-recursive] Error 1
     199    make[1]: Leaving directory '/tmp/shuuji3/spack-stage/spack-stage-gfarm2fs-main-rboxdyz5vhfkby4qa2i63wzv3k3veou4/spack-src'
     200    make: *** [Makefile:403: all] Error 2

</pre>
</details>

I tried installing it on RHEL 7.7, then a similar but slightly different error occurred:

<summery>Errors on RHEL 7.7:</summery>
<details>
<pre>
(...)

6 errors found in build log:
     187    mv -f .deps/xattr.Tpo .deps/xattr.Po
     188    /bin/sh ./libtool  --tag=CC   --mode=link /home/NBB/shuuji3/spack/lib/spack/env/gcc/gcc
             -Wall -g -O2  -L/home/NBB/shuuji3/spack/opt/spack/linux-rhel7-haswell/gcc-4.8.5/gfarm-
            main-qmwdkudjvm2s6uyhwwz6cxad7suvdffv/lib -o gfarm2fs_fix_acl gfarm2fs_fix_acl.o acl.o 
            id.o xattr.o gfarm_config.o  -lfuse -lgfarm -lgfarm
     189    libtool: link: /home/NBB/shuuji3/spack/lib/spack/env/gcc/gcc -Wall -g -O2 -o gfarm2fs_f
            ix_acl gfarm2fs_fix_acl.o acl.o id.o xattr.o gfarm_config.o  -L/home/NBB/shuuji3/spack/
            opt/spack/linux-rhel7-haswell/gcc-4.8.5/gfarm-main-qmwdkudjvm2s6uyhwwz6cxad7suvdffv/lib
             -lfuse -lgfarm
     190    mv -f .deps/gfarm2fs.Tpo .deps/gfarm2fs.Po
     191    /bin/sh ./libtool  --tag=CC   --mode=link /home/NBB/shuuji3/spack/lib/spack/env/gcc/gcc
             -Wall -g -O2  -L/home/NBB/shuuji3/spack/opt/spack/linux-rhel7-haswell/gcc-4.8.5/gfarm-
            main-qmwdkudjvm2s6uyhwwz6cxad7suvdffv/lib -o gfarm2fs gfarm2fs.o acl.o id.o replicate.o
             open_file.o xattr.o gfarm_config.o  -lfuse -lgfarm -lgfarm
     192    libtool: link: /home/NBB/shuuji3/spack/lib/spack/env/gcc/gcc -Wall -g -O2 -o gfarm2fs g
            farm2fs.o acl.o id.o replicate.o open_file.o xattr.o gfarm_config.o  -L/home/NBB/shuuji
            3/spack/opt/spack/linux-rhel7-haswell/gcc-4.8.5/gfarm-main-qmwdkudjvm2s6uyhwwz6cxad7suv
            dffv/lib -lfuse -lgfarm
  >> 193    /usr/bin/ld: gfarm2fs.o: undefined reference to symbol 'pthread_rwlock_wrlock@@@@GLIBC_2.
            2.5'
  >> 194    //usr/lib64/libpthread.so.0: error adding symbols: DSO missing from command line
  >> 195    collect2: error: ld returned 1 exit status
  >> 196    make[2]: *** [gfarm2fs] Error 1
     197    make[2]: Leaving directory `/tmp/shuuji3/spack-stage/spack-stage-gfarm2fs-main-wxbuqqir
            ujjelvg2xjshjmsfqdntd3sv/spack-src'
  >> 198    make[1]: *** [all-recursive] Error 1
     199    make[1]: Leaving directory `/tmp/shuuji3/spack-stage/spack-stage-gfarm2fs-main-wxbuqqir
            ujjelvg2xjshjmsfqdntd3sv/spack-src'
  >> 200    make: *** [all] Error 2
</pre>
</details>

**Comment by otatebe** [comment]
It works for me on Debian stable.  Does it happen only on Debian unstable?
Also does /lib/x86_64-linux-gnu/libpthread.so include pthread_rwlock_destroy?

**Comment by onlyjob** [comment]
> It works for me on Debian stable. Does it happen only on Debian unstable?

Yes the problem affects "unstable". "stable" have no `libgfarm-dev (>= 2.7.15~)` so I can't try to build there and even if I could, "unstable" still exhibits the problem.

> Also does `/lib/x86_64-linux-gnu/libpthread.so` include `pthread_rwlock_destroy`?

How can I check that?

**Comment by otatebe** [comment]
try % nm /lib/x86_64-linux-gnu/libpthread.so.0 | grep rwlock

**Comment by onlyjob** [comment]
```
$ nm /lib/x86_64-linux-gnu/libpthread.so.0 | grep rwlock
000000000000dac0 t __GI___pthread_rwlock_rdlock
000000000000efd0 t __GI___pthread_rwlock_unlock
000000000000e280 t __GI___pthread_rwlock_wrlock
000000000000dab0 T __pthread_rwlock_destroy
000000000000da70 T __pthread_rwlock_init
000000000000dac0 T __pthread_rwlock_rdlock
000000000000eec0 T __pthread_rwlock_tryrdlock
000000000000ef70 T __pthread_rwlock_trywrlock
000000000000efd0 T __pthread_rwlock_unlock
000000000000e280 T __pthread_rwlock_wrlock
0000000000018010 r default_rwlockattr
000000000000dfb0 T pthread_rwlock_clockrdlock
000000000000ea40 T pthread_rwlock_clockwrlock
000000000000dab0 T pthread_rwlock_destroy
000000000000da70 T pthread_rwlock_init
000000000000dac0 W pthread_rwlock_rdlock
000000000000dd20 T pthread_rwlock_timedrdlock
000000000000e640 T pthread_rwlock_timedwrlock
000000000000eec0 T pthread_rwlock_tryrdlock
000000000000ef70 T pthread_rwlock_trywrlock
000000000000efd0 W pthread_rwlock_unlock
000000000000e280 W pthread_rwlock_wrlock
000000000000f1b0 T pthread_rwlockattr_destroy
000000000000f1f0 T pthread_rwlockattr_getkind_np
000000000000f1c0 T pthread_rwlockattr_getpshared
000000000000f1a0 T pthread_rwlockattr_init
000000000000f200 T pthread_rwlockattr_setkind_np
000000000000f1d0 T pthread_rwlockattr_setpshared
```

This is with `libc6_2.31-9`.

**Comment by otatebe** [comment]
Thanks.  Try 2bf894c8b6acf6106834b22993cf5000dd137b2d and do autoreconf, configure and make again.  I hope this fixes your problem.

**Comment by onlyjob** [comment]
With 2bf894c 1.2.14 builds fine [on all architectures](https://buildd.debian.org/status/package.php?p=gfarm2fs) in Debian.

Thanks!
